PrivateKey: ""
Network: "mainnet" # mainnet or testnet
RpcUrl: "https://mempool.space/api" #https://mempool.space/api https://mempool.space/testnet/api
FeePerByte: 10
UtxoAmount: 0
Etching:
  Rune: "STUDYZY"
  Symbol: "曾"
  Premine: 1000000
  Amount: 1000
  Cap: 20000
#  Divisibility: 0
#  HeightStart: 0
#  HeightEnd: 0
#  HeightOffsetStart: 0
#  HeightOffsetEnd: 0
Mint:
  RuneId: "840000:65"